config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'tv_shows#index'
  resources :tv_shows, only: [:index] do
    member do
      post :mark_favorite 
    end
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :tv_shows
end

app/models/favorite_show.rb
class FavoriteShow < ApplicationRecord
  belongs_to :user
  belongs_to :tv_show
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
  belongs_to :channel
  has_many :favorite_shows

  def self.search(params)
    self.joins(:channel).
      search_by_tv_show_or_channel(params[:tv_show_or_channel])
  end

  def self.search_by_tv_show_or_channel(tv_show_or_channel)
    if tv_show_or_channel.blank?
      self.where(nil)
    else
      self.where("tv_shows.show_name LIKE ? OR channels.name LIKE ?", "%#{tv_show_or_channel}%", "%#{tv_show_or_channel}%")
    end
  end

  def favorite(user)
    self.favorite_shows.where(user_id: user.id).present? ? 'Unmark' : 'Mark'
  end

  def mark_favorite(user)
    if self.favorite_shows.where(user_id: user.id).present?
      self.favorite_shows.where(user_id: user.id).destroy_all
    else
      self.favorite_shows.create(user_id: user.id)
    end
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorite_shows

  has_many :tv_shows, through: :favorite_shows
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController

  def index
    @tv_shows = TvShow.search(params)
  end

  def mark_favorite
    @tv_show = TvShow.find(params[:id])
    @tv_show.mark_favorite(current_user)
    redirect_to tv_shows_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tv_shows_helper.rb
module TvShowsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TvShows</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tv_shows/index.html.erb
<div>
  
  <div id='search_panel'>
    <%= form_tag tv_shows_path, method: 'GET' do %>
      <label>TV Show / Channel</label>
      <%= text_field_tag :tv_show_or_channel, params[:tv_show_or_channel] %>
      <%= submit_tag "search" %>
    <% end %>

  <%= @tv_shows.count %> records found
  </div>
  <div id='results'>
    <table>
      <thead>
        <tr>
          <th>Channel Name</th>
          <th> TV Show</th>
          <th>Start Time</th>
          <th>End Time</th>
          <th>Favorite</th>
        </tr>
      </thead>
      <tbody>
        <% if @tv_shows.present? %>
          <% @tv_shows.each do |t| %>
            <tr>
              <td><%= t.channel.name %></td>
              <td><%= t.show_name %></td>
              <td><%= t.start_time.strftime("%H:%M") %></td>
              <td><%= t.end_time.strftime("%H:%M") %></td>
              <td id="<%= "favorite_#{t.id}" %>"><%= button_to(t.favorite(current_user), mark_favorite_tv_show_path(t)) %></td>
            </tr>
          <% end %>
        <% else %>
          <tr><td colspan="5">No show found</td></tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/tv_shows/mark_favorite.js.erb
$('#favorite_<%= @tv_show.id%>').html('<%= escape_javascript button_to(@tv_show.favorite(current_user), mark_favorite_tv_show_path(@tv_show), remote: true) %>');